package lint

import (
	"go/ast"
	"go/token"
	"reflect"
	"strings"

	"golang.org/x/tools/go/analysis"
)

var IsGeneratedAnalyzer = &analysis.Analyzer{
	Name: "isgenerated",
	Doc:  "annotate *ast.File that have been code generated",
	Run: func(pass *analysis.Pass) (interface{}, error) {
		m := map[*ast.File]bool{}
		for _, f := range pass.Files {
			if len(f.Comments) > 0 {
				comment := f.Comments[0].Text()
				b := strings.Contains(comment, "Code generated by") ||
					strings.Contains(comment, "DO NOT EDIT")
				m[f] = b
			}
		}
		return m, nil
	},
	RunDespiteErrors: true,
	ResultType:       reflect.TypeOf(map[*ast.File]bool{}),
}

var TokenFileAnalyzer = &analysis.Analyzer{
	Name: "tokenfileanalyzer",
	Doc:  "creates a mapping of *token.File to *ast.File",
	Run: func(pass *analysis.Pass) (interface{}, error) {
		m := map[*token.File]*ast.File{}
		for _, af := range pass.Files {
			tf := pass.Fset.File(af.Pos())
			m[tf] = af
		}
		return m, nil
	},
	RunDespiteErrors: true,
	ResultType:       reflect.TypeOf(map[*token.File]*ast.File{}),
}
